### ISSUE TITLE
[bug] game crashed But not exit to desktop

### ISSUE THREAD

**Issue by ywgATustcbbs** [ReactiveDrop/reactivedrop_public_src#332] opened 2022-10-04 14:22 UTC
https://user-images.githubusercontent.com/11514506/193843572-a26fb8ae-410d-4d81-b4dc-7ad2d414f3c1.mp4

Please open the sound, the game sounds like looping.

This is a serious bug. The game crashed But not exited. I can't open taskmgr to force kill the process because the game overlayed on top of all Windows. I can only force restarting my pc. No memory dump is created.

The bug happened often these days, one or two times daily. Usually happed after several hours of hosting lobby.

Don't think it is related to my hardware because one of my friend encountered it when we were plying.

However,i will list my hardware in case it is useful. R7 3900x, asus x570e, 16gx2, rtx2070s, plextor m9peg 1t

**Comment by mithrand0** [comment] 2022-10-04 14:49
This almost looks like a crashed video or audio driver. Any traces of such thing in the Windows Event Logs?

**Comment by ywgATustcbbs** [comment] 2022-10-04 15:22
> This almost looks/sounds like a crashed video or audio driver. Any traces of such thing in the Windows Event Logs?

nothing helpful.

this is software failure events
![1](https://user-images.githubusercontent.com/11514506/193859214-d49b4cff-2df9-4405-8380-a6fca9840404.PNG)


this is system failure events
![2](https://user-images.githubusercontent.com/11514506/193859480-e1694922-7e3a-4761-8b7c-53b2f28d4399.PNG)


no hardware failure/warning events

**Comment by ywgATustcbbs** [comment] 2022-10-04 15:32
> This almost looks/sounds like a crashed video or audio driver. Any traces of such thing in the Windows Event Logs?

Btw, i was talking with friends on voice call on my computer, the voice call never dropped while the game was looping. Start menu displayed correctly, background software working fine, only be blocked by the game. The game was running under full screen mode.

**Comment by ywgATustcbbs** [comment] 2022-10-05 04:29
> This almost looks/sounds like a crashed video or audio driver. Any traces of such thing in the Windows Event Logs?

Happened again 


https://user-images.githubusercontent.com/11514506/193981538-a0a96697-67b1-4e11-90ef-2e5343207478.mp4

**Comment by mithrand0** [comment] 2022-10-12 12:29
No free edicts mean you did hit the entity limit in Source Engine.

https://developer.valvesoftware.com/wiki/Entity_limit

This should certainly not be possible without mods. Do you have workshop items or mods installed that you can uninstall to check if that fixes it?

**Comment by mithrand0** [comment] 2023-11-07 14:10
Didn't receive any update. 

The issue is also so old, that I think we can safely close it.

**Closed by mithrand0** 2023-11-07 14:10 UTC
Labels: bug, need more information, client
